"DS218+":
  prefix:
    - "1970"
  middle:
    - "PCN"
  suffix: "numeric"
  ports: "1"
"DS220+":
  prefix:
    - "2230"
  middle:
    - "RLR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "2"
"DS224+":
  prefix:
    - "2350"
  middle:
    - "WBR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "2"
"DS423+":
  prefix:
    - "2350"
  middle:
    - "VKR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "2"
"DS718+":
  prefix:
    - "1880"
  middle:
    - "PEN"
  suffix: "numeric"
  ports: "2"
"DS720+":
  prefix:
    - "2010"
  middle:
    - "QWR"
  suffix: "alpha"
  ports: "2"
"DS723+":
  prefix:
    - "2230"
  middle:
    - "TPR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "2"
"DS918+":
  prefix:
    - "1890"
  middle:
    - "PDN"
  suffix: "numeric"
  ports: "2"
"DS920+":
  prefix:
    - "2120"
  middle:
    - "SBR"
  suffix: "alpha"
  ports: "2"
"DS923+":
  prefix:
    - "2270"
  middle:
    - "TQR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "2"
"DS1019+":
  prefix:
    - "1880"
  middle:
    - "QXR"
  suffix: "numeric"
  ports: "2"
"DS1520+":
  prefix:
    - "2060"
  middle:
    - "RYR"
  suffix: "alpha"
  ports: "4"
"DS1522+":
  prefix:
    - "2270"
  middle:
    - "TRR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "4"
"DS1621+":
  prefix:
    - "2080"
  middle:
    - "S7R"
  suffix: "alpha"
  ports: "4"
"DS1621xs+":
  prefix:
    - "2070"
  middle:
    - "RVR"
  suffix: "alpha"
  ports: "3"
"DS1819+":
  prefix:
    - "2050"
  middle:
    - "R5R"
  suffix: "alpha"
  ports: "4"
"DS1821+":
  prefix:
    - "2230"
  middle:
    - "SKR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "4"
"DS1823xs+":
  prefix:
    - "2280"
  middle:
    - "V5R"
  suffix: "alpha"
  macpre: 9009d0
  ports: "4"
"DS2419+":
  prefix:
    - "1880"
  middle:
    - "QZR"
  suffix: "alpha"
  ports: "4"
"DS2422+":
  prefix:
    - "2180"
  middle:
    - "SLR"
  suffix: "alpha"
  ports: "4"
"DS3617xs":
  prefix:
    - "1891"
  middle:
    - "ODN"
  suffix: "numeric"
  ports: "4"
"DS3622xs+":
  prefix:
    - "21A0"
  middle:
    - "SQR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "5"
"DVA1622":
  prefix:
    - "2280"
  middle:
    - "UBR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "1"
"DVA3219":
  prefix:
    - "1930"
  middle:
    - "RFR"
  suffix: "alpha"
  ports: "4"
"DVA3221":
  prefix:
    - "2280"
  middle:
    - "SJR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "4"
"FS2500":
  prefix:
    - "1960"
  middle:
    - "PSN"
  suffix: "numeric"
  ports: "4"
"FS6400":
  prefix:
    - "0000"
  middle:
    - "XXX"
  suffix: "alpha"
  ports: "4"
"HD6500":
  prefix:
    - "21C0"
  middle:
    - "RUR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "5"
"RS422+":
  prefix:
    - "2210"
  middle:
    - "TSR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "2"
"RS820rp+":
  prefix:
    - "1960"
  middle:
    - "RAR"
  suffix: "alpha"
  ports: "4"
"RS1221+":
  prefix:
    - "20B0"
  middle:
    - "RWR"
  suffix: "alpha"
  ports: "4"
"RS1619xs+":
  prefix:
    - "1920"
  middle:
    - "QPR"
  suffix: "alpha"
  ports: "4"
"RS2821RP+":
  prefix:
    - "20C0"
  middle:
    - "SMR"
  suffix: "alpha"
  ports: "8"
"RS3618xs":
  prefix:
    - "2320"
  middle:
    - "QNR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "4"
"RS3621xs+":
  prefix:
    - "20A0"
  middle:
    - "SZR"
  suffix: "alpha"
  ports: "6"
"RS4021xs+":
  prefix:
    - "2310"
  middle:
    - "ULR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "6"
"SA3200d":
  prefix:
    - "19A0"
  middle:
    - "S4R"
  suffix: "alpha"
  ports: "6"
"SA3400":
  prefix:
    - "1970"
  middle:
    - "RJR"
  suffix: "alpha"
  ports: "6"
"SA3600":
  prefix:
    - "2150"
  middle:
    - "RSR"
  suffix: "alpha"
  ports: "6"
"SA6400":
  prefix:
    - "2270"
  middle:
    - "UMR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "7"
"SA3410":
  prefix:
    - "2270"
  middle:
    - "UMR"
  suffix: "alpha"
  macpre: 9009d0
  ports: "7"