#
# Copyright (C) 2025 AuxXxilium <https://github.com/AuxXxilium>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Update Data

on:
  workflow_dispatch:
    inputs:
      runs:
        description: "runs-on"
        type: choice
        options:
          - ubuntu-latest
          - self-hosted
      cleanfiles:
        description: 'clean files'
        default: false
        type: boolean

jobs:
  dsm-files:
    runs-on: ${{ inputs.runs }}
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          swap-storage: false

      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1

      - name: Initialization environment
        run: |
          sudo git config --global user.email "info@auxxxilium.tech"
          sudo git config --global user.name "AuxXxilium"
          sudo timedatectl set-timezone "Europe/Berlin"

          sudo apt-get update -qq
          sudo apt-get install -y \
            jq \
            build-essential \
            libtool \
            pkgconf \
            libzstd-dev \
            liblzma-dev \
            libssl-dev \
            gawk \
            cpio \
            gettext \
            libelf-dev \
            qemu-utils \
            busybox \
            dialog \
            curl \
            sed \
            zip \
            unzip \
            python3-full
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          PYTHON_LIB="$(dirname "$(realpath "$(which python3)")")"
          sudo mv -f "${PYTHON_LIB}/EXTERNALLY-MANAGED" "${PYTHON_LIB}/EXTERNALLY-MANAGED.bak" 2>/dev/null || true
          sudo pip3 install -q -U -r scripts/requirements.txt

      - name: Clean Files
        if: inputs.cleanfiles == true
        run: sudo rm -rf ./files ./dsm

      - name: Download configs
        run: |
          sudo rm -rf -- ./configs
          mkdir -p ./configs
          curl --insecure -fsSL "https://raw.githubusercontent.com/AuxXxilium/arc-configs/main/platforms.yml" \
            -o ./configs/platforms.yml

      - name: Update
        run: sudo ./update.sh

  rebuild-data:
    needs: dsm-files
    uses: ./.github/workflows/rebuild-data.yml
    with:
      runs: ${{ inputs.runs }}
